trigger:
  tags:
    include:
    - 'v*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    pip install -e .[testing]
  displayName: Install dependencies

- script: |
    pytest
  displayName: Test with pytest

- script: |
    pip install setuptools sdist wheel twine
    pip install -r requirements.txt
    python setup.py sdist bdist_wheel
  displayName: Build

- task: CopyFiles@2
  displayName: Copy dist files
  inputs:
    contents: 'dist/**'
    targetFolder: $(Build.ArtifactStagingDirectory)

- publish: '$(Build.ArtifactStagingDirectory)/dist'
  displayName: 'Publish artifacts'
  artifact: pypack-guide
