on:
  workflow_dispatch:
    inputs:
      org:
        description: 'Organisation Name: '
        required: true
        type: string
        default: 'leoleung0900'

      proj:
        description: 'Project Name: '
        required: true
        type: string
        default: 'pypack-guide'

      feed:
        description: 'Feed Name: '
        required: true
        type: string
        default: 'pypack-guide-publish'

name: Test Package Installation

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install Package
        env:
          proj: ${{ github.event.inputs.proj }}
          org: ${{ github.event.inputs.org }}
          pat: ${{ secrets.PAT }}
          feed: ${{ github.event.inputs.feed }}
        run: |
          pip install "$proj" -i https://"$org":"$pat"@pkgs.dev.azure.com/"$org"/"$proj"/_packaging/"$feed"/pypi/simple
