name: Tag Release

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
          
      - name: Install dependencies
        run: |
          pip install -e .[testing]
          
      - name: Test with pytest
        run: |
          pytest
          
      - name: Build
        run: |
          pip install setuptools sdist wheel twine
          pip install -r requirements.txt
          python setup.py sdist bdist_wheel

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ./dist/*tar.gz
            ./dist/*.whl
